/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.mihosoft.ext.velocity.legacy;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
